services:
  # MySQL数据库
  db:
    image: mysql:8.0
    container_name: pyresume_db
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: ${TZ:-Asia/Shanghai}
    ports:
      - "${DB_PORT_EXTERNAL}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - pyresume_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USER}", "-p${DB_PASSWORD}"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s
    command: --default-authentication-plugin=mysql_native_password

  # Django后端
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: pyresume_backend
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - EMAIL_BACKEND=${EMAIL_BACKEND}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USE_SSL=${EMAIL_USE_SSL}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - TZ=${TZ:-Asia/Shanghai}
      - GUNICORN_WORKERS=${GUNICORN_WORKERS:-3}
      - GUNICORN_TIMEOUT=${GUNICORN_TIMEOUT:-120}
    ports:
      - "${BACKEND_PORT}:8000"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      db:
        condition: service_healthy
    networks:
      - pyresume_network
    restart: unless-stopped

  # React前端
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    container_name: pyresume_frontend
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend  # 添加对后端的依赖
    networks:
      - pyresume_network
    restart: unless-stopped


volumes:
  mysql_data:
    driver: local
  static_volume:
    driver: local
  media_volume:
    driver: local

networks:
  pyresume_network:
    driver: bridge