# Generated by Django 5.2.5 on 2025-09-02 07:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyresume', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user', '-created_at'], name='pyresume_ap_user_id_035022_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['user', '-created_at'], name='pyresume_co_user_id_0c3299_idx'),
        ),
    ]
