"""init tables

Revision ID: 9faafc0d9179
Revises: 
Create Date: 2025-08-16 15:29:45.016120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9faafc0d9179'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_platforms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform_name', sa.String(length=100), nullable=False, comment='平台名称'),
    sa.Column('website_url', sa.String(length=255), nullable=False, comment='网站URL'),
    sa.Column('login_type', sa.String(length=255), nullable=False, comment='登录方式'),
    sa.Column('username', sa.String(length=100), nullable=True, comment='登录用户名'),
    sa.Column('encrypted_password', sa.String(length=255), nullable=True, comment='加密后的密码'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注信息'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否活跃(1:是,0:否)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False, comment='公司名称'),
    sa.Column('position_name', sa.String(length=100), nullable=True, comment='职位名称'),
    sa.Column('application_status', sa.Enum('已投递', '测评中', '笔试中', '一面', '二面', '三面', '已结束', 'offer', name='application_status_enum'), nullable=False, comment='投递状态'),
    sa.Column('base_location', sa.String(length=50), nullable=True, comment='工作地点'),
    sa.Column('resume_content', sa.Text(), nullable=True, comment='简历内容'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注信息'),
    sa.Column('platform_id', sa.Integer(), nullable=True, comment='求职平台ID'),
    sa.ForeignKeyConstraint(['platform_id'], ['job_platforms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_applications')
    op.drop_table('job_platforms')
    # ### end Alembic commands ###
