# Generated by Django 5.2.5 on 2025-08-31 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('website_link', models.URLField(blank=True, null=True)),
                ('login_type', models.CharField(blank=True, max_length=100, null=True)),
                ('uname', models.CharField(blank=True, max_length=100, null=True)),
                ('upass', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('position', models.TextField(blank=True, null=True)),
                ('base', models.TextField(blank=True, null=True)),
                ('salery', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('resume', models.TextField(blank=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pyresume.company')),
            ],
        ),
    ]
